### ISSUE TITLE
I like to add Modern Card design in home page with Beautiful Box Shadow

### ISSUE THREAD

**Issue by Ayushpanditmoto** [collabnix/devops#29]
Please Assign me this task

**Comment by collabnix** [comment]
Hi, @Ayushpanditmoto Thanks for showing interest to improve this site.
I have assigned you to this issue. 

Looking forward to your contribution.

**Comment by Rohith-Raju** [comment]
@Ayushpanditmoto Please go ahead, and feel free to ask me if you run into any problems
