### ISSUE TITLE
Margin isssue

### ISSUE THREAD

**Issue by Ayushpanditmoto** [collabnix/devops#31]
I like to fix margin issue please assign me this task

![Screenshot_13](https://user-images.githubusercontent.com/31253617/195013285-77e88487-c0f7-497a-abe8-1d079a5b0533.png)
![Screenshot_12](https://user-images.githubusercontent.com/31253617/195013296-65c9d9ac-48ec-4d69-8689-f0910fe33abb.png)

**Comment by Rohith-Raju** [comment]
Sure @Ayushpanditmoto, go ahead

**Comment by Rohith-Raju** [comment]
@Ayushpanditmoto it looks fine on my end.
![image](https://user-images.githubusercontent.com/55309324/195283756-8de7fb74-97e2-4731-bb0b-0b8e300001da.png)

**Comment by Ayushpanditmoto** [comment]
i am still facing padding or margin issue 
[issues Video](https://youtu.be/79Kc9aavdRI)

can u tell where this component present 
i failed to found that component where i have to add padding

**Comment by Rohith-Raju** [comment]
ok @Ayushpanditmoto, you'll have to go through the dev tools. @ajeetraina does this problem exist in your end?

**Comment by Rohith-Raju** [comment]
I haven't changed any default Docusaurus layouts. Could you test in other browser, this problem shouldn't exist
